using UnityEditor;
using UnityEngine;

namespace Cyberkanoid.GameObjects.Model.common
{
    /// <summary>
    /// Base class for all Game objects
    /// </summary>
    public abstract class BaseModel
    {
        #region Fileds
        protected readonly GUID id;
        protected bool isActive = false;
        protected Vector3 position;
        #endregion

        #region Constructors
        /// <summary>
        /// Create new Model with precreated ID
        /// </summary>
        /// <param name="id"></param>
        public BaseModel(GUID id)
        {
            this.id = id;
        }
        /// <summary>
        /// Create new model without pregenerated ID. ID generated by model itself
        /// </summary>
        protected BaseModel()
        {
            id = GUID.Generate();
        }
        #endregion

        #region Properiies
        public GUID Id
        {
            get
            {
                return id;
            }
        }
        /// <summary>
        /// Activity stae of the Object. 
        /// True = fully functional on the scene 
        /// False = has no scene functions, but still is stored in Objcet Pool
        /// </summary>
        public bool IsActive
        {
            get => isActive;
            set => IsActive = value;
        }
        /// <summary>
        /// Current object position on a scene
        /// </summary>
        public Vector3 Position
        {
            get
            {
                return position;
            }

            set
            {
                position = value;
            }
        }
        #endregion
    }
}
